sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
script:
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - mkdir build
  - cd build
  - cmake .. -G "Unix Makefiles"
  - make -j 4

